# Generated by Django 6.0.7 on 2026-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='loaction',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='tittle',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('hired', 'Hired'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
