# Generated by Django 6.0.7 on 2026-07-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application',
            new_name='applicant',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('shortlisted', 'Shortlisted'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='pending', max_length=20),
        ),
    ]
